language: python
python:
  - "3.7"

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PYTHONPATH=yugiohbot

services:
  - docker

addons:
  apt:
    update: true

cache:
  directories:
  - $HOME/google-cloud-sdk

before_install:
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components install beta
  - gcloud components update
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM}/terraform_${TERRAFORM}_linux_amd64.zip
  - unzip terraform_${TERRAFORM}_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform --version

script:
  - chmod +x deployment/deploy.sh
  - ./deployment/deploy.sh
