language: python
python:
  - "3.7"

env:
  - PYTHONPATH=yugiohbot

services:
  - docker

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y zip unzip
  - mkdir -p ~/bin
  - curl -SL https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip > chromedriver.zip
  - unzip chromedriver.zip -d ~/bin/
  - curl -SL https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-37/stable-headless-chromium-amazonlinux-2017-03.zip > headless-chromium.zip
  - unzip headless-chromium.zip -d ~/bin/
  - chmod +x ~/bin/headless-chromium
  - chmod +x ~/bin/chromedriver
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM}/terraform_${TERRAFORM}_linux_amd64.zip
  - unzip terraform_${TERRAFORM}_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform --version
  - pip install -r requirements.txt
  - pip install awscli
  - aws --version

script:
  - pytest --cov=./
  - mkdir package
  - pip install -r requirements.txt -t package/
  - cp ~/bin/chromedriver package/bin/
  - cp ~/bin/headless-chromium package/bin/
  - cp -a yugiohbot/. package/
  - chmod +x ./integration.sh
  - chmod +x ./deployment/deploy.sh

after_script:
  - codecov
  - cd package
  - zip -r ../package.zip *
  - ../deployment/deploy.sh